import localFont from "next/font/local";
import "./globals.css";
import HomePageCards from './HomePage/HomePageCards';
import HomeTitle from "./HomePage/HomeTitle";
import HomeVideo from "./HomePage/HomeVideo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Home() {
  return (
    <div>
      <HomeTitle/>
      <HomePageCards/>
      <HomeVideo/>
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Home/>
        </body>
    </html>
  );
}
