import localFont from "next/font/local";
import "./globals.css";
import HomePageCards from './HomePage/HomePageCards';
import HomeVideo from "./HomePage/HomeVideo";
import Footer from "./Footer";
import { CLIENT_STATIC_FILES_RUNTIME_POLYFILLS_SYMBOL } from "next/dist/shared/lib/constants";
import AboutUs from "./HomePage/AboutUs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Home() {
  return (
    <div>
      <HomeVideo/>
      <HomePageCards/>
      <AboutUs/>
      <Footer/>
    </div>
  );
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Home/>
        </body>
    </html>
  );
}
